--liquibase formatted sql

--changeset pixels:furniture-seed-posture-metadata-0046 context:development
create temporary table posture_review(id bigint primary key,name text not null,status text not null,confidence text not null,source text not null,reason text not null,previous_allow_sit boolean not null,previous_allow_lay boolean not null) on commit drop;
insert into posture_review values
(800044,'17_ww_pillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(800160,'Angel_Baby_Pink_Sofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800201,'Atlanta_Elayne_Bed_1','lay','high','visual_review','Cama o hamaca claramente acostable.',false,false),
(800252,'Atlanta_Japandi_Bed_1','lay','high','visual_review','Cama o hamaca claramente acostable.',false,false),
(800281,'Atlanta_Japandi_Hammock','lay','high','visual_review','Cama o hamaca claramente acostable.',false,false),
(800295,'Atlanta_Japandi_Pillow_2','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(800296,'Atlanta_Japandi_Pillow_3','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(800318,'Atlanta_Japandi_Rattan_Chair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800494,'BW_HeadmasterChair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800520,'BW_Hogwartsdiningbench','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800521,'BW_Hufflepouf','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800523,'BW_HufflepuffChair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800526,'BW_HufflepuffSofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800566,'BW_SlytherinArmchair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800568,'BW_SlytherinChair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800574,'BW_SlytherinStool','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800576,'BW_SlytherinThrone','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800582,'BW_TeacherChair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800586,'BW_TrainSofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800589,'BW_diningbench','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800600,'Barrel_Stool','sit','medium','visual_review','El nombre funcional identifica un asiento; el icono no estaba disponible.',false,false),
(800756,'BobbaCouch','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800792,'Bubblejuice_throne_Atlanta','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800901,'Cama_japo','lay','high','visual_review','Cama o hamaca claramente acostable.',false,false),
(800911,'Chaise_de_bar_argent','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800912,'Chaise_de_bar_noire','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800913,'Chaise_de_bar_or','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(800999,'Cupid_chair','sit','medium','visual_review','El nombre funcional identifica un asiento; el icono no estaba disponible.',false,false),
(801084,'Dark_green_sofa','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(801101,'Diofante_Banco','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(801386,'GrimmauldChair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(801388,'GrimmauldSofa','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(801888,'Habblet_carebears_bed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(802895,'Irinc_Diofante_Cama','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(803208,'Machi_original41_JPseat','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(803234,'Mansion_Christmas_Pillow','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(803511,'Noel_c20_City_RocheChaise','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(803648,'Pirates_Bench','sit','medium','visual_review','El nombre funcional identifica un asiento; el icono no estaba disponible.',false,false),
(803653,'Pirates_Stool','sit','medium','visual_review','El nombre funcional identifica un asiento; el icono no estaba disponible.',false,false),
(803921,'Sillon_Cuero_Cheapy4','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(803955,'Sofa_grande','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(804254,'Wniverso_Sofa_Natalino','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(804271,'Wniverso_sofa_Ursinho_natalino','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(804343,'Yvess5_Ascenseur_Flit','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(804866,'Yvess5_Tennis_Chaise','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(805385,'aeki_23_pillow_01','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(805386,'aeki_23_pillow_01_01','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(805520,'anc16_sofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(805527,'anc_comfy_tree','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(805543,'angel_bgpink_flip_chair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(805544,'angel_blue_flip_chair','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(805575,'angel_white_stool','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(805650,'antoh_xs_casinothrone','sit','medium','visual_review','El nombre funcional identifica un asiento; el icono no estaba disponible.',false,false),
(805868,'art_c20_pillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(806005,'autumn_c20_tree2','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(806050,'azul_h17_sofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(806224,'banco_cmnto_plano','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(808792,'bonusrare19_2*4','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(808793,'bonusrare19_2*5','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(809408,'burd_h17_sofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(809426,'bw_hogwartsbench','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(809452,'byesw_hand','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(809878,'cc_zebra_couch','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(811077,'cstm_f24_cute_bearybed','lay','high','visual_review','Cama o hamaca claramente acostable.',false,false),
(811090,'cstm_f24_cute_polarpillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(811249,'cstm_j21_grunge_couch_r','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(811554,'cuer_h17_sofa','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(812323,'durm_bench','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(812568,'easter_c22_fossilbench','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(812743,'easter_r16_throne','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(813823,'garden_flowerbed','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(814195,'gracie_24_stool_01_01','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(814457,'habblet_mel_chairminibed','lay','medium','visual_review','El icono muestra una cama claramente acostable.',false,false),
(815012,'habbox_chair_hancar','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(815123,'habbox_coral_seabed_details','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(815202,'habbox_cupid_woodchair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(819043,'habbox_viking_stool','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(820089,'hlive_c25_hwcraftingbed','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(820182,'hlive_clr25_dinersofa','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(820509,'hotel_pillow','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(820529,'hp_bench','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(820531,'hp_bigchair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(820703,'hp_smallchair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(821235,'hween_c20_floatingbed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(821678,'india_c20_eleseat','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(821685,'india_c20_longpillow','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(821807,'irinc_mario_chair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(821815,'irinc_mario_junglebed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(821900,'irinc_shadow_lgbtchair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(822089,'jp_bed','lay','high','furniture_data','FurnitureData declara canLayOn=true.',false,false),
(822342,'kasja_cf_smileypillow','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(822392,'kasja_g_flowerbed','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(822442,'kasja_mansionplay_daybed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(822463,'kasja_s_bench','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(822829,'legendary16_chair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(823625,'mansion_purple5_throne','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(823737,'matcha_f25_chair_02','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(823845,'mel_hellokittypillow','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(823933,'mel_shellpillow','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(824101,'mini_flower_pillow_marion','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(824598,'mystics_bbed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(824610,'mystics_gbed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(824723,'neon_pillow_by_jonas','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(824857,'nest_bed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(825365,'nft_sc24_hotelit','none','medium','visual_review','El icono no muestra una superficie de asiento.',false,false),
(825379,'nft_u23_sonft_sofa','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(825887,'oliver_cstm_tennis_judge_chair','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(826029,'orientala19r_chair','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(826063,'origins_c24_pirate_bed_one','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(826064,'origins_c24_pirate_bed_two','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(826410,'pcnc_tree','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(826682,'pink_ribbon_pillow','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(827106,'plta_h17_sofa','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(829463,'rainbow_throne','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(830747,'rare_samuraipillow','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(830749,'rare_samuraithrone','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(830764,'rav3_colourable_pillow','none','low','visual_review','No se pudo recuperar el icono; clasificación conservadora.',false,false),
(830838,'recycler_patchpillow','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(831396,'rusticroots_workbench','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(831505,'sanrio_c22_keroppisofa','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(831507,'sanrio_c22_mymelodybed','lay','high','visual_review','El icono muestra una cama claramente acostable.',false,false),
(832011,'shadow_lgbtchair','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(832290,'shtrdl_greenhouse_seedbed_1x1','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832291,'shtrdl_greenhouse_seedbed_2x1','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832418,'sleepy_24_bed_back_01','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832419,'sleepy_24_bed_back_corner_01','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832420,'sleepy_24_bed_back_desk_01','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832421,'sleepy_24_bed_back_desk_01_01','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832422,'sleepy_24_bed_back_desk_02_01','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(832523,'sofa_hogwarts','sit','medium','visual_review','El icono muestra un asiento claro.',false,false),
(833208,'stef_crystalthrone','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(833225,'stone_flowerbed','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(833594,'test_effectswitch','lay','high','furniture_data','FurnitureData declara canLayOn=true.',false,false),
(833651,'thai_c21_pillow','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(833691,'throne_bed_black','lay','medium','visual_review','El icono muestra una cama claramente acostable.',false,false),
(833692,'throne_bed_green','lay','medium','visual_review','El icono muestra una cama claramente acostable.',false,false),
(833693,'throne_bed_purple','lay','medium','visual_review','El icono muestra una cama claramente acostable.',false,false),
(834829,'waasa_hbct_bed','none','medium','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(834864,'wean_fauteuil','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(834871,'wean_pouf','sit','medium','visual_review','El icono muestra un asiento claro.',false,false),
(835880,'xmas_c16_tinybed','lay','high','furniture_data','FurnitureData declara canLayOn=true.',false,false),
(835903,'xmas_c17_engage_ted','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(835973,'xmas_c19_balcony','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(836640,'zombie_memorial_chair','none','high','visual_review','El icono no muestra una superficie apta para postura.',false,false),
(970064,'Atlanta_scandi_bench_2','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(970209,'DIY_a174_SakuraCookingBench','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(970213,'DIY_a178_WaterChair','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(970234,'DIY_a265_ChickenPillow','sit','medium','visual_review','El icono muestra un asiento definido.',false,false),
(971022,'Sofa_Cartier','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(971238,'Yvess5_DJ20_Pouf','sit','medium','visual_review','El icono muestra un asiento claro.',false,false),
(971748,'auxiliarbanco','none','medium','visual_review','Cojín bajo sin asiento definido.',false,false),
(972437,'bedrum_23_stool_01','sit','high','visual_review','Asiento claramente visible en el icono.',false,false),
(972517,'black_ruffle_bed','lay','high','visual_review','Cama o hamaca claramente acostable.',false,false),
(973490,'cstm_hw16_pillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(973544,'cstm_m20_pillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(973545,'cstm_m_pillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(973552,'cstm_old_greek_pillow','none','high','visual_review','Almohada o adorno sin superficie de asiento.',false,false),
(974068,'fest_c19_loverstent','lay','high','furniture_data','FurnitureData declara canLayOn=true.',false,false),
(975439,'habcrush_c18_wiltedplantbed','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(975554,'hblooza14_planepadb','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(975555,'hblooza14_planepadr','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(976193,'irinc_pablok_flowerbed','none','high','visual_review','El icono no muestra una superficie de asiento.',false,false),
(976368,'kasja_s_stool','sit','high','visual_review','El icono muestra un asiento definido.',false,false),
(976722,'market_c19_trolley','sit','high','furniture_data','FurnitureData declara canSitOn=true.',false,false),
(977221,'nft_xmas11_throne','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977410,'orien_stoel_klein','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977430,'origins_c25_heartsofa_black','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977431,'origins_c25_heartsofa_blue','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977432,'origins_c25_heartsofa_green','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977433,'origins_c25_heartsofa_pink','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977434,'origins_c25_heartsofa_white','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(977435,'origins_c25_heartsofa_yellow','sit','high','visual_review','El icono muestra un asiento claro.',false,false),
(978726,'test_tent','lay','high','furniture_data','FurnitureData declara canLayOn=true.',false,false)
;
create temporary table posture_guard(definitions_match boolean constraint posture_review_definitions_must_match check(definitions_match),manual_metadata_free boolean constraint posture_review_must_not_override_manual_metadata check(manual_metadata_free)) on commit drop;
insert into posture_guard select (select count(*) from posture_review review join furniture_definitions definition on definition.id=review.id and definition.name=review.name and definition.deleted_at is null)=(select count(*) from posture_review),not exists(select 1 from posture_review review join furniture_definitions definition on definition.id=review.id where jsonb_exists(definition.metadata,'slots') or coalesce((definition.metadata->'posture'->>'manual_override')::boolean,false));
update furniture_definitions definition set allow_sit=definition.allow_sit or review.status='sit',allow_lay=definition.allow_lay or review.status='lay',metadata=jsonb_set(definition.metadata,'{posture}',jsonb_build_object('audit_id','pixelados-2026-07-25','version',1,'source',review.source,'status',review.status,'confidence',review.confidence,'reason',review.reason,'strategy',case when review.status='none' then 'none' else 'derived_footprint' end,'manual_override',true),true),updated_at=now(),version=definition.version+1 from posture_review review where definition.id=review.id;
update furniture_definitions definition set metadata=jsonb_set(definition.metadata,'{posture}',jsonb_build_object('audit_id','pixelados-2026-07-25','version',1,'source',case when jsonb_exists(definition.metadata,'slots') then 'explicit_slots' else 'definition_flags' end,'status',case when definition.allow_sit and definition.allow_lay then 'sit_lay' when definition.allow_lay then 'lay' when definition.allow_sit then 'sit' else 'none' end,'confidence',case when jsonb_exists(definition.metadata,'slots') then 'high' when definition.allow_sit or definition.allow_lay then 'medium' else 'unclassified' end,'strategy',case when jsonb_exists(definition.metadata,'slots') then 'explicit_slots' when definition.allow_sit or definition.allow_lay then 'derived_footprint' else 'none' end,'manual_override',false),true),updated_at=now(),version=definition.version+1 where definition.deleted_at is null and not jsonb_exists(definition.metadata,'posture');
--rollback update furniture_definitions set allow_sit=false where id in (800160,800318,800494,800520,800521,800523,800526,800566,800568,800574,800576,800582,800586,800589,800600,800756,800792,800911,800912,800913,800999,801084,801101,801386,801388,803208,803234,803648,803653,803921,803955,804254,804271,804866,805520,805527,805543,805544,805575,805650,806005,806050,806224,808792,808793,809408,809426,809452,809878,811249,811554,812323,812568,812743,814195,815012,815202,819043,820182,820509,820529,820531,820703,821678,821685,821807,821900,822342,822463,822829,823625,823737,823845,823933,824723,825379,825887,826029,826410,827106,829463,830749,831505,832011,832523,833208,834864,834871,835903,835973,970064,970213,970234,971022,971238,972437,975554,975555,976368,976722,977221,977410,977430,977431,977432,977433,977434,977435); update furniture_definitions set allow_lay=false where id in (800201,800252,800281,800901,801888,802895,811077,814457,821235,821815,822089,822442,824598,824610,824857,826063,826064,831507,833594,833691,833692,833693,835880,972517,974068,978726); update furniture_definitions set metadata=metadata-'posture' where metadata->'posture'->>'audit_id'='pixelados-2026-07-25';
